blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('blog/', views.PostList.as_view(), name='home'),
    path('', views.welcome, name='welcome'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('like/<slug:slug>', views.post_like, name='post_like'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit')
]

devmark/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("about/", include("about.urls"),name="about_urls"),
    path("tools/", include("tools.urls"),name="tools_urls"),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path("accounts/", include("allauth.urls")),
]

tools/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('tools/', views.ToolsList.as_view(), name='tools'),
    path('<slug:slug>/', views.tools_detail, name='tools_detail'),
]

tools/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg
from cloudinary.models import CloudinaryField

STATUS = ((0,"Draft"), (1,"Published"))

# Create your models here.

class Tools(models.Model):
    name = models.CharField(max_length=200, unique = True)
    link = models.URLField(max_length=200, unique = True)
    slug = models.SlugField(max_length=200, unique = True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tool_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    def average_rating(self) -> float:
        return Rating.objects.filter(tools=self).aggregate(Avg("rating"))["rating__avg"] or 0

    def __str__(self):
        return f"{self.name}: {self.average_rating()}"


   
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tools = models.ForeignKey(Tools, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.tools.name}: {self.rating}"

tools/views.py
from django.shortcuts import (render, get_object_or_404,
                              reverse, HttpResponse, redirect)
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Tools, Rating


class ToolsList(generic.ListView):
    model = Tools
    queryset = Tools.objects.filter(status=1).order_by('-created_on')
    template_name = 'tools.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tool_list = context['object_list']
        ratings = [tool.average_rating() for tool in tool_list]
        context['ratings'] = ratings
        return context


def tools_detail(request, slug, *args, **kwargs):
    """
    A function-based view to view the detail of a tools.
    """

    queryset = Tools.objects.filter(status=1)
    tools = get_object_or_404(queryset, slug=slug)
    rating = rating

    return render(
        request,
        "tools_detail.html",
        {
            "tools": tools,
            "rating": rating,
        },
    )

tools/templates/tools.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Tools Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for tools in tools_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in tools.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ tools.featured_image.url }}" alt="{{tools.name}}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ tools.author }}</p>
                                </div>
                            </div>
                            <a href="#" class="tools">
                                <h2 class="card-title">{{ tools.name }}</h2>
                                <p class="card-text">{{ tools.excerpt }}</p>
                                <p class="card-rating">Average Rating: {{ tools.average_rating }}<i class="fa-solid fa-star"></i></p>
                                <p>Tool Ratings by Users</p>
                                <ul>
                                    {% for rating in tools.rating_set.all %}
                                        <li>{{ rating.user.username }}: {{ rating.rating }}</li>
                                    {% endfor %}
                                </ul>
                            </a>
                            <hr>
                            <p class="card-text text-muted h6">{{ tools.created_on }}</p>
                            
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

tools/templates/tools_detail.html
{% extends 'base.html' %} 

{% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Tools title goes in these h1 tags -->
                <h1 class="tools-title">{{ tools.title }}</h1>
                </h1>
                <!-- Tools author goes before the | the post's created date goes after -->
                <p class="tools-subtitle">{{ tools.author }} | {{ tools.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in tools.featured_image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src=" {{ tools.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ tools.content | safe }}
                </p>
                <div class="col-1">
                    <strong>
                        {% if user.is_authenticated %}
                        <form class="d-inline" action="{% url 'tools_detail' tools.slug %}" method="POST">
                            {% csrf_token %}
                            {% if liked %}
                            <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                            {% else %}
                            <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                            {% endif %}
                        </form>
                        {% else %}
                        <span class="text-secondary"><i class="far fa-heart"></i></span>
                        {% endif %}
                    <!-- The number of likes goes before the closing strong tag -->
                    <span class="text-secondary">{{ post.number_of_likes }} </span>
                    </strong>
                </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
</div>

{% endblock content %}

{% block extras %}
{% load static %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock extras %}